### PR TITLE
Initial Packaging

### LINKED ISSUE #2: Missing packaging
To easily install this tool, it would be create to install it directly from pip or at least from GitHub CI. A `pyproject.toml`

### PR DESCRIPTION
**Pull request by 1Maxnet1**
Resolves #2

Should allow to install the tool and run it via command line afterwards

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -18,26 +18,27 @@ almost any database system; So far it's been used with SQLite, Postgres, and Mic
...
 
 ### Example Use
+Installation via `pip install -e .`
 
 1. **Bay Area Rapid Transit with GTFS-realtime TripUpdates:**
 
    a. Using SQLite:
 
-       gtfsrdb.py -t http://api.bart.gov/gtfsrt/tripupdate.aspx -d sqlite:///test.db -c
+       gtfsrdb -t http://api.bart.gov/gtfsrt/tripupdate.aspx -d sqlite:///test.db -c
```
Comment (maexled) [inline README.md:27]: URL throws 403, maybe use http://api.tampa.onebusaway.org:8088/trip-updates for testing

**Review by maexled — COMMENTED** [review]
Works with Python 3.12, with Python 3.10 following error occurs:
`Exception occurred in iteration
(<class 'AttributeError'>, AttributeError("module 'datetime' has no attribute 'UTC'"), <traceback object at 0x7f862ae32a40>)`
